### PR TITLE
test: remove tests for deprecated command

### PR DESCRIPTION
**Pull request by gssbzn**
## Proposed changes

Remove tests for deprecated command, this commands have been deprecated for a while and they are starting to flake so better to remove them

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have updated [e2e/E2E-TESTS.md](e2e/E2E-TESTS.md) (if a new command or e2e test has been added)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by andreaangiolillo — DISMISSED** [review]
I don't agree with this decision as I think that if we provide this functionality to our customers we should test it (if possible). In my opinion, if we decide to remove the test we should also remote the command.
No Blocking, this is only my opinion.

**Review by colm-quinn — APPROVED** [review]
LGTM, also q, is there an entry that needs to be removed/changed in `E2e-TESTS.md` as a result of this?

**Comment by gssbzn** [comment]
> is there an entry that needs to be removed/changed in E2e-TESTS.md as a result of this?

good call, I deleted the entries as we don't even document these commands any more, we should plan some time to start deleting some of the deprecated stuff

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Pull request merged**
