### PR TITLE
CLOUDP-82830: Enable ifshort as a linter

### PR DESCRIPTION
**Pull request by gssbzn**
## Proposed changes

_Jira ticket:_ CLOUDP-82830

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

## Further comments

We were already doing this except tests which looks like a lot of copy/paste is to blame

### CODE REVIEW

**Comment by andreaangiolillo** [comment]
You're missing some of them 

Screenshot 2021-02-17 at 10 07 18

**Comment by gssbzn** [comment]
>You're missing some of them
😞

**Comment by gssbzn** [comment]
@andreaangiolillo should be RFAL, no idea how I was able to commit and my githook pre commit did not catch that

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Pull request merged**
