### PR TITLE
CLOUDP-112815: Updating om-go client to latest release

### PR DESCRIPTION
**Pull request by andreaangiolillo**
## Proposed changes

_Jira ticket:_ CLOUDP-112815

## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation in document requirements section listed in [CONTRIBUTING.md](https://github.com/mongodb/mongocli/blob/master/CONTRIBUTING.md) (if appropriate)
- [x] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [x] I have updated [e2e/E2E-TESTS.md](https://github.com/mongodb/mongocli/blob/master/e2e/E2E-TESTS.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

## Further comments

This ticket updates the om go client to the latest release to get the fix in https://github.com/mongodb/go-client-mongodb-ops-manager/pull/138

### CODE REVIEW

**Review by gssbzn — APPROVED** [review]
LGTM

**Comment by andreaangiolillo** [comment]
evergreen retry

**Comment by andreaangiolillo** [comment]
@gssbzn Do you know how to start the docs check here?

**Comment by andreaangiolillo** [comment]
docs retry

**Pull request merged**
