### PR TITLE
Updated cobra2snooty

### PR DESCRIPTION
**Pull request by andreaangiolillo**
## Checklist

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have addressed the @mongodb/docs-cloud-team comments (if appropriate)
- [x] I have updated [e2e/E2E-TESTS.md](e2e/E2E-TESTS.md) (if an e2e test has been added)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Review by gssbzn — DISMISSED** [review]
LGTM if LGTDOCS

**Review by JuliaMongo — APPROVED** [review]
LGTM. For the other PR, it would be nice to add a period at the end of "This value defaults to X.", but if too late, at least we now have a sentence.

**Comment by andreaangiolillo** [comment]
Sure

**Comment by andreaangiolillo** [comment]
@JuliaMongo I have addressed your comment.

**Review by JuliaMongo — APPROVED** [review]

**Pull request merged**
