### PR TITLE
CLOUDP-80931: Update Data Lake create to support AWS roles

### PR DESCRIPTION
**Pull request by gssbzn**
## Proposed changes

_Jira ticket:_ CLOUDP-80931 

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

### CODE REVIEW

**Comment by gssbzn** [comment]
there seems to be some bug in the API, checking this internally

**Review by threebee — APPROVED** [review]
LGTM! `golangci-lint (push)` job was failing so I have restarted it.

**Comment by gssbzn** [comment]
@threebee yes, is timing out, I guess we have a large codebase now, I have this PR if you want to approve as well, https://github.com/mongodb/mongocli/pull/589

**Review by andreaangiolillo — APPROVED** [review]
LGTM

**Pull request merged**
